# Generated by Django 2.2.7 on 2019-11-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191115_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subway',
            old_name='source',
            new_name='sauce',
        ),
    ]
