# Generated by Django 2.2.7 on 2019-11-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
