# Generated by Django 2.2.7 on 2019-11-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salse',
            new_name='Sales',
        ),
    ]
