# Generated by Django 2.2.7 on 2019-11-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0002_auto_20191127_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcohol',
            name='people',
            field=models.ManyToManyField(through='manytomany.Sales', to='manytomany.Person'),
        ),
    ]
